// Generated by CoffeeScript 1.9.2
(function() {
  var _;

  _ = {};

  _.each = function(collection, callback) {
    var i, key, len, num, results, results1, val;
    if (Array.isArray(collection)) {
      results = [];
      for (i = 0, len = collection.length; i < len; i++) {
        num = collection[i];
        results.push(callback(num));
      }
      return results;
    } else {
      results1 = [];
      for (key in collection) {
        val = collection[key];
        results1.push(callback(val));
      }
      return results1;
    }
  };

  module.exports = _;

}).call(this);
